"""Project Scaffold Agent.

Creates the project directory tree, configuration files, entry points,
.gitignore, .env.example, and README.md based on the approved blueprint.
"""

import json
from pathlib import Path

from tasks.a2a_agent_utils import begin_agent_session, publish_agent_output
from tasks.privileged_control import (
    append_privileged_audit_event,
    build_privileged_policy,
    path_allowed,
)
from tasks.utils import OUTPUT_DIR, llm, log_task_update, write_text_file


AGENT_METADATA = {
    "project_scaffold_agent": {
        "description": (
            "Creates the project directory tree, configuration files, entry points, "
            ".gitignore, .env.example, and README from an approved blueprint."
        ),
        "skills": ["scaffolding", "project setup", "config generation"],
        "input_keys": ["blueprint_json", "project_root", "project_name"],
        "output_keys": ["scaffold_created_files", "scaffold_status", "scaffold_summary"],
        "requirements": [],
    },
}


def _strip_code_fences(text: str) -> str:
    stripped = (text or "").strip()
    if stripped.startswith("```") and stripped.endswith("```"):
        lines = stripped.splitlines()
        if len(lines) >= 2:
            return "\n".join(lines[1:-1]).strip()
    return stripped


def _create_directory_tree(root: Path, structure: list[str]) -> list[str]:
    """Create directories and empty stub files. Returns list of created paths."""
    created: list[str] = []
    for entry in structure:
        target = root / entry
        if entry.endswith("/"):
            target.mkdir(parents=True, exist_ok=True)
            created.append(str(target))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            if not target.exists():
                target.write_text("", encoding="utf-8")
                created.append(str(target))
    return created


def _generate_gitignore(tech_stack: dict) -> str:
    language = str(tech_stack.get("language", "")).lower()
    lines = [
        "# Dependencies",
        "node_modules/",
        "__pycache__/",
        "*.pyc",
        ".venv/",
        "venv/",
        "",
        "# Environment",
        ".env",
        ".env.local",
        ".env.*.local",
        "",
        "# Build",
        "dist/",
        "build/",
        ".next/",
        "*.egg-info/",
        "",
        "# IDE",
        ".idea/",
        ".vscode/",
        "*.swp",
        "*.swo",
        "",
        "# OS",
        ".DS_Store",
        "Thumbs.db",
        "",
        "# Docker",
        "docker-compose.override.yml",
    ]
    if "python" in language:
        lines.extend(["", "# Python", "*.egg", "*.whl", ".mypy_cache/", ".ruff_cache/", ".pytest_cache/"])
    if "typescript" in language or "javascript" in language:
        lines.extend(["", "# TypeScript/JS", "*.tsbuildinfo", "coverage/"])
    return "\n".join(lines) + "\n"


def _generate_env_example(env_vars: list[dict]) -> str:
    lines = ["# Environment Variables", "# Copy to .env and fill in values", ""]
    for ev in env_vars:
        name = ev.get("name", "UNKNOWN")
        desc = ev.get("description", "")
        example = ev.get("example_value", "")
        if desc:
            lines.append(f"# {desc}")
        lines.append(f"{name}={example}")
        lines.append("")
    return "\n".join(lines)


def _generate_readme(blueprint: dict) -> str:
    name = blueprint.get("project_name", "project")
    tech = blueprint.get("tech_stack", {})
    endpoints = blueprint.get("api_design", {}).get("endpoints", [])

    lines = [
        f"# {name}",
        "",
        f"**Stack**: {tech.get('framework', 'unknown')} + {tech.get('database', 'unknown')}",
        "",
        "## Quick Start",
        "",
        "```bash",
        "# Start database",
        "docker-compose up -d",
        "",
        "# Install dependencies",
    ]
    pm = tech.get("package_manager", "npm")
    if "pip" in pm:
        lines.extend(["pip install -r requirements.txt", ""])
    if "npm" in pm:
        lines.extend(["npm install", ""])
    lines.extend([
        "# Run development server",
        "# See .env.example for required environment variables",
        "```",
        "",
    ])
    if endpoints:
        lines.append("## API Endpoints")
        lines.append("")
        for ep in endpoints[:20]:
            lines.append(f"- `{ep.get('method', '?')} {ep.get('path', '?')}` -- {ep.get('description', '')}")
        lines.append("")
    lines.append("---")
    lines.append("Generated by SuperAgent Project Builder.")
    return "\n".join(lines) + "\n"


def _generate_config_file(blueprint: dict, file_type: str) -> str:
    """Use LLM to generate a config file appropriate for the stack."""
    tech = blueprint.get("tech_stack", {})
    deps = blueprint.get("dependencies", {})
    prompt = f"""
Generate the content for a {file_type} configuration file for a project with this tech stack:
{json.dumps(tech, indent=2)}

Dependencies:
{json.dumps(deps, indent=2)}

Project name: {blueprint.get('project_name', 'app')}

Return ONLY the file content, no explanation, no markdown fences.
""".strip()
    response = llm.invoke(prompt)
    raw = response.content if hasattr(response, "content") else str(response)
    return _strip_code_fences(raw).strip() + "\n"


def project_scaffold_agent(state):
    """Create the project skeleton from the approved blueprint."""
    active_task, task_content, _ = begin_agent_session(state, "project_scaffold_agent")
    state["project_scaffold_agent_calls"] = state.get("project_scaffold_agent_calls", 0) + 1
    call_number = state["project_scaffold_agent_calls"]

    blueprint = state.get("blueprint_json", {})
    if not blueprint:
        raise ValueError("project_scaffold_agent requires blueprint_json in state.")

    project_root = Path(state.get("project_root", "")).resolve()
    if not project_root or str(project_root) == ".":
        raise ValueError("project_scaffold_agent requires project_root in state.")

    privileged_policy = build_privileged_policy(state)
    if privileged_policy.get("read_only", False):
        raise PermissionError("project_scaffold_agent blocked: privileged read-only mode.")
    if not path_allowed(str(project_root), privileged_policy.get("allowed_paths", [])):
        raise PermissionError(f"project_scaffold_agent blocked: {project_root} outside allowed scope.")

    tech_stack = blueprint.get("tech_stack", {})
    directory_structure = blueprint.get("directory_structure", [])
    env_vars = blueprint.get("env_vars", [])
    log_task_update("Scaffold", f"Scaffolding pass #{call_number} started at {project_root}.")

    # 1. Create directory tree
    project_root.mkdir(parents=True, exist_ok=True)
    created_files = _create_directory_tree(project_root, directory_structure)

    # 2. Generate .gitignore
    gitignore_path = project_root / ".gitignore"
    gitignore_path.write_text(_generate_gitignore(tech_stack), encoding="utf-8")
    created_files.append(str(gitignore_path))

    # 3. Generate .env.example
    if env_vars:
        env_path = project_root / ".env.example"
        env_path.write_text(_generate_env_example(env_vars), encoding="utf-8")
        created_files.append(str(env_path))

    # 4. Generate README.md
    readme_path = project_root / "README.md"
    readme_path.write_text(_generate_readme(blueprint), encoding="utf-8")
    created_files.append(str(readme_path))

    # 5. Generate main config file (package.json / pyproject.toml)
    language = str(tech_stack.get("language", "")).lower()
    if "python" in language:
        config_content = _generate_config_file(blueprint, "pyproject.toml")
        config_path = project_root / "pyproject.toml"
        config_path.write_text(config_content, encoding="utf-8")
        created_files.append(str(config_path))

        # Also write requirements.txt
        runtime_deps = blueprint.get("dependencies", {}).get("runtime", [])
        python_deps = [d for d in runtime_deps if not str(d).startswith("npm:")]
        if python_deps:
            req_path = project_root / "requirements.txt"
            req_path.write_text("\n".join(python_deps) + "\n", encoding="utf-8")
            created_files.append(str(req_path))

    if "typescript" in language or "javascript" in language or tech_stack.get("package_manager") in ("npm", "yarn", "pnpm"):
        config_content = _generate_config_file(blueprint, "package.json")
        pkg_root = project_root
        # For full-stack projects, check if there's a frontend/ subdirectory
        if "+" in language and (project_root / "frontend").exists():
            pkg_root = project_root / "frontend"
        config_path = pkg_root / "package.json"
        config_path.write_text(config_content, encoding="utf-8")
        created_files.append(str(config_path))

        # tsconfig.json
        ts_config = _generate_config_file(blueprint, "tsconfig.json")
        ts_path = pkg_root / "tsconfig.json"
        ts_path.write_text(ts_config, encoding="utf-8")
        created_files.append(str(ts_path))

    # Persist results
    state["scaffold_created_files"] = created_files
    state["scaffold_status"] = "completed"
    summary = f"Scaffolded {len(created_files)} files/directories at {project_root}."
    state["scaffold_summary"] = summary
    state["draft_response"] = summary

    append_privileged_audit_event(
        state,
        actor="project_scaffold_agent",
        action="scaffold",
        status="completed",
        detail={"project_root": str(project_root), "file_count": len(created_files)},
    )
    write_text_file(f"scaffold_output_{call_number}.txt", summary + "\n\n" + "\n".join(created_files))
    log_task_update("Scaffold", f"Scaffold complete: {len(created_files)} items created.", summary)

    state = publish_agent_output(
        state,
        "project_scaffold_agent",
        summary,
        f"scaffold_result_{call_number}",
        recipients=["orchestrator_agent", "reviewer_agent"],
    )
    return state
