"""Express + Prisma + PostgreSQL stack template."""

STACK_TEMPLATE = {
    "name": "express_prisma_postgres",
    "display_name": "Express + Prisma + PostgreSQL",
    "tech_stack": {
        "language": "typescript",
        "framework": "express",
        "database": "postgresql",
        "orm": "prisma",
        "migration_tool": "prisma",
        "auth": "jwt",
        "css": None,
        "package_manager": "npm",
        "runtime": "ts-node",
    },
    "base_directory_structure": [
        "src/",
        "src/index.ts",
        "src/routes/",
        "src/routes/index.ts",
        "src/controllers/",
        "src/services/",
        "src/middleware/",
        "src/middleware/auth.ts",
        "src/middleware/errorHandler.ts",
        "src/middleware/validate.ts",
        "src/lib/",
        "src/lib/prisma.ts",
        "src/types/",
        "src/types/index.ts",
        "prisma/",
        "prisma/schema.prisma",
        "tests/",
        "docker/",
    ],
    "base_dependencies": {
        "runtime": [
            "express",
            "@prisma/client",
            "jsonwebtoken",
            "bcryptjs",
            "zod",
            "cors",
            "helmet",
            "dotenv",
            "morgan",
        ],
        "dev": [
            "typescript",
            "@types/node",
            "@types/express",
            "@types/jsonwebtoken",
            "@types/bcryptjs",
            "@types/cors",
            "@types/morgan",
            "prisma",
            "ts-node",
            "tsx",
            "nodemon",
            "jest",
            "@types/jest",
            "ts-jest",
            "eslint",
            "@typescript-eslint/parser",
            "@typescript-eslint/eslint-plugin",
        ],
    },
    "base_env_vars": [
        {
            "name": "DATABASE_URL",
            "description": "PostgreSQL connection string for Prisma",
            "example_value": "postgresql://postgres:postgres@localhost:5432/appdb",
            "required": True,
        },
        {
            "name": "JWT_SECRET",
            "description": "JWT signing secret",
            "example_value": "change-me-in-production",
            "required": True,
        },
        {
            "name": "PORT",
            "description": "Server port",
            "example_value": "3000",
            "required": False,
        },
    ],
    "base_docker_services": [
        {
            "name": "postgres",
            "image": "postgres:16-alpine",
            "ports": ["5432:5432"],
            "volumes": ["pgdata:/var/lib/postgresql/data"],
            "env": {
                "POSTGRES_USER": "postgres",
                "POSTGRES_PASSWORD": "postgres",
                "POSTGRES_DB": "appdb",
            },
        },
    ],
}
