"""FastAPI + SQLAlchemy + PostgreSQL + Alembic stack template."""

STACK_TEMPLATE = {
    "name": "fastapi_postgres",
    "display_name": "FastAPI + PostgreSQL",
    "template_dir": "project_templates/fastapi_postgres",
    "tech_stack": {
        "language": "python",
        "framework": "fastapi",
        "database": "postgresql",
        "orm": "sqlalchemy",
        "migration_tool": "alembic",
        "auth": "jwt",
        "css": None,
        "package_manager": "pip",
        "runtime": "uvicorn",
    },
    "base_directory_structure": [
        "app/",
        "app/__init__.py",
        "app/main.py",
        "app/api/",
        "app/api/__init__.py",
        "app/api/routes/",
        "app/api/routes/__init__.py",
        "app/api/deps.py",
        "app/core/",
        "app/core/__init__.py",
        "app/core/config.py",
        "app/core/security.py",
        "app/db/",
        "app/db/__init__.py",
        "app/db/session.py",
        "app/db/base.py",
        "app/models/",
        "app/models/__init__.py",
        "app/schemas/",
        "app/schemas/__init__.py",
        "app/services/",
        "app/services/__init__.py",
        "alembic/",
        "alembic/versions/",
        "alembic/env.py",
        "tests/",
        "tests/__init__.py",
        "tests/conftest.py",
        "docker/",
    ],
    "base_dependencies": {
        "runtime": [
            "fastapi>=0.110",
            "uvicorn[standard]>=0.29",
            "sqlalchemy[asyncio]>=2.0",
            "asyncpg>=0.29",
            "alembic>=1.13",
            "pydantic>=2.6",
            "pydantic-settings>=2.2",
            "python-jose[cryptography]>=3.3",
            "passlib[bcrypt]>=1.7",
            "python-dotenv>=1.0",
            "python-multipart>=0.0.9",
        ],
        "dev": [
            "pytest>=8.0",
            "pytest-asyncio>=0.23",
            "httpx>=0.27",
            "ruff>=0.3",
            "mypy>=1.9",
        ],
    },
    "base_env_vars": [
        {
            "name": "DATABASE_URL",
            "description": "PostgreSQL async connection string",
            "example_value": "postgresql+asyncpg://postgres:postgres@localhost:5432/appdb",
            "required": True,
        },
        {
            "name": "SECRET_KEY",
            "description": "JWT signing secret",
            "example_value": "change-me-in-production",
            "required": True,
        },
        {
            "name": "ACCESS_TOKEN_EXPIRE_MINUTES",
            "description": "JWT token lifetime in minutes",
            "example_value": "30",
            "required": False,
        },
    ],
    "base_docker_services": [
        {
            "name": "postgres",
            "image": "postgres:16-alpine",
            "ports": ["5432:5432"],
            "volumes": ["pgdata:/var/lib/postgresql/data"],
            "env": {
                "POSTGRES_USER": "postgres",
                "POSTGRES_PASSWORD": "postgres",
                "POSTGRES_DB": "appdb",
            },
        },
    ],
}
