"""FastAPI + React/Vite + SQLAlchemy + PostgreSQL full-stack template."""

STACK_TEMPLATE = {
    "name": "fastapi_react_postgres",
    "display_name": "FastAPI + React + PostgreSQL (Full-Stack)",
    "tech_stack": {
        "language": "python+typescript",
        "framework": "fastapi+react",
        "database": "postgresql",
        "orm": "sqlalchemy",
        "migration_tool": "alembic",
        "auth": "jwt",
        "css": "tailwindcss",
        "package_manager": "pip+npm",
        "runtime": "uvicorn+vite",
    },
    "base_directory_structure": [
        # Backend
        "backend/",
        "backend/app/",
        "backend/app/__init__.py",
        "backend/app/main.py",
        "backend/app/api/",
        "backend/app/api/__init__.py",
        "backend/app/api/routes/",
        "backend/app/api/routes/__init__.py",
        "backend/app/api/deps.py",
        "backend/app/core/",
        "backend/app/core/__init__.py",
        "backend/app/core/config.py",
        "backend/app/core/security.py",
        "backend/app/db/",
        "backend/app/db/__init__.py",
        "backend/app/db/session.py",
        "backend/app/db/base.py",
        "backend/app/models/",
        "backend/app/models/__init__.py",
        "backend/app/schemas/",
        "backend/app/schemas/__init__.py",
        "backend/app/services/",
        "backend/app/services/__init__.py",
        "backend/alembic/",
        "backend/alembic/versions/",
        "backend/tests/",
        "backend/tests/__init__.py",
        # Frontend
        "frontend/",
        "frontend/src/",
        "frontend/src/main.tsx",
        "frontend/src/App.tsx",
        "frontend/src/index.css",
        "frontend/src/components/",
        "frontend/src/components/ui/",
        "frontend/src/pages/",
        "frontend/src/hooks/",
        "frontend/src/lib/",
        "frontend/src/lib/api.ts",
        "frontend/src/types/",
        "frontend/src/types/index.ts",
        "frontend/public/",
        # Shared
        "docker/",
    ],
    "base_dependencies": {
        "runtime": [
            # Backend (pip)
            "fastapi>=0.110",
            "uvicorn[standard]>=0.29",
            "sqlalchemy[asyncio]>=2.0",
            "asyncpg>=0.29",
            "alembic>=1.13",
            "pydantic>=2.6",
            "pydantic-settings>=2.2",
            "python-jose[cryptography]>=3.3",
            "passlib[bcrypt]>=1.7",
            "python-dotenv>=1.0",
            "python-multipart>=0.0.9",
            # Frontend (npm) -- prefixed with npm:
            "npm:react@latest",
            "npm:react-dom@latest",
            "npm:react-router-dom",
            "npm:axios",
            "npm:tailwindcss",
            "npm:postcss",
            "npm:autoprefixer",
            "npm:lucide-react",
        ],
        "dev": [
            "pytest>=8.0",
            "pytest-asyncio>=0.23",
            "httpx>=0.27",
            "ruff>=0.3",
            "mypy>=1.9",
            "npm:typescript",
            "npm:@types/react",
            "npm:@types/react-dom",
            "npm:@vitejs/plugin-react",
            "npm:vite",
            "npm:eslint",
        ],
    },
    "base_env_vars": [
        {
            "name": "DATABASE_URL",
            "description": "PostgreSQL async connection string",
            "example_value": "postgresql+asyncpg://postgres:postgres@localhost:5432/appdb",
            "required": True,
        },
        {
            "name": "SECRET_KEY",
            "description": "JWT signing secret",
            "example_value": "change-me-in-production",
            "required": True,
        },
        {
            "name": "VITE_API_URL",
            "description": "Backend API base URL for the React frontend",
            "example_value": "http://localhost:8000",
            "required": False,
        },
    ],
    "base_docker_services": [
        {
            "name": "postgres",
            "image": "postgres:16-alpine",
            "ports": ["5432:5432"],
            "volumes": ["pgdata:/var/lib/postgresql/data"],
            "env": {
                "POSTGRES_USER": "postgres",
                "POSTGRES_PASSWORD": "postgres",
                "POSTGRES_DB": "appdb",
            },
        },
    ],
}
