"""MERN + microservices + MongoDB stack template."""

STACK_TEMPLATE = {
    "name": "mern_microservices_mongodb",
    "display_name": "MERN + Microservices + MongoDB",
    "tech_stack": {
        "language": "typescript",
        "framework": "express+react",
        "database": "mongodb",
        "orm": "mongoose",
        "migration_tool": "none",
        "auth": "jwt",
        "css": "tailwindcss",
        "package_manager": "npm",
        "runtime": "node+vite",
    },
    "base_directory_structure": [
        # Frontend
        "frontend/",
        "frontend/src/",
        "frontend/src/main.tsx",
        "frontend/src/App.tsx",
        "frontend/src/index.css",
        "frontend/src/components/",
        "frontend/src/pages/",
        "frontend/src/lib/",
        "frontend/src/lib/api.ts",
        "frontend/src/types/",
        "frontend/public/",
        # API gateway
        "services/",
        "services/api-gateway/",
        "services/api-gateway/src/",
        "services/api-gateway/src/index.ts",
        "services/api-gateway/src/routes/",
        "services/api-gateway/src/middleware/",
        "services/api-gateway/src/lib/",
        # Microservices
        "services/auth-service/",
        "services/auth-service/src/",
        "services/auth-service/src/index.ts",
        "services/auth-service/src/routes/",
        "services/auth-service/src/models/",
        "services/catalog-service/",
        "services/catalog-service/src/",
        "services/catalog-service/src/index.ts",
        "services/catalog-service/src/routes/",
        "services/catalog-service/src/models/",
        "services/orders-service/",
        "services/orders-service/src/",
        "services/orders-service/src/index.ts",
        "services/orders-service/src/routes/",
        "services/orders-service/src/models/",
        "services/inventory-service/",
        "services/inventory-service/src/",
        "services/inventory-service/src/index.ts",
        "services/inventory-service/src/routes/",
        "services/inventory-service/src/models/",
        "services/notifications-service/",
        "services/notifications-service/src/",
        "services/notifications-service/src/index.ts",
        # Shared package utilities
        "packages/",
        "packages/shared-types/",
        "packages/shared-types/src/",
        "packages/shared-types/src/index.ts",
        "packages/shared-config/",
        "packages/shared-config/src/",
        "packages/shared-config/src/index.ts",
        # Infra and scripts
        "infra/",
        "infra/docker/",
        "infra/docker/docker-compose.yml",
        "infra/k8s/",
        "scripts/",
    ],
    "base_dependencies": {
        "runtime": [
            "express",
            "mongoose",
            "jsonwebtoken",
            "bcryptjs",
            "cors",
            "helmet",
            "dotenv",
            "morgan",
            "zod",
            "axios",
            "react",
            "react-dom",
            "react-router-dom",
            "tailwindcss",
        ],
        "dev": [
            "typescript",
            "tsx",
            "nodemon",
            "vitest",
            "@types/node",
            "@types/express",
            "@types/jsonwebtoken",
            "@types/bcryptjs",
            "@types/cors",
            "@types/morgan",
            "@types/react",
            "@types/react-dom",
            "eslint",
            "@typescript-eslint/parser",
            "@typescript-eslint/eslint-plugin",
            "vite",
            "@vitejs/plugin-react",
        ],
    },
    "base_env_vars": [
        {
            "name": "NODE_ENV",
            "description": "Runtime environment",
            "example_value": "development",
            "required": False,
        },
        {
            "name": "GATEWAY_PORT",
            "description": "API gateway port",
            "example_value": "3000",
            "required": True,
        },
        {
            "name": "FRONTEND_PORT",
            "description": "Frontend dev server port",
            "example_value": "5173",
            "required": False,
        },
        {
            "name": "JWT_SECRET",
            "description": "JWT signing secret shared across auth-aware services",
            "example_value": "change-me-in-production",
            "required": True,
        },
        {
            "name": "MONGODB_URI_AUTH",
            "description": "MongoDB URI for auth service",
            "example_value": "mongodb://localhost:27017/authdb",
            "required": True,
        },
        {
            "name": "MONGODB_URI_CATALOG",
            "description": "MongoDB URI for catalog service",
            "example_value": "mongodb://localhost:27017/catalogdb",
            "required": True,
        },
        {
            "name": "MONGODB_URI_ORDERS",
            "description": "MongoDB URI for orders service",
            "example_value": "mongodb://localhost:27017/ordersdb",
            "required": True,
        },
        {
            "name": "MONGODB_URI_INVENTORY",
            "description": "MongoDB URI for inventory service",
            "example_value": "mongodb://localhost:27017/inventorydb",
            "required": True,
        },
        {
            "name": "REDIS_URL",
            "description": "Redis URL for caching and queue use-cases",
            "example_value": "redis://localhost:6379/0",
            "required": False,
        },
        {
            "name": "NATS_URL",
            "description": "NATS URL for async service-to-service messaging",
            "example_value": "nats://localhost:4222",
            "required": False,
        },
    ],
    "base_docker_services": [
        {
            "name": "mongodb",
            "image": "mongo:7",
            "ports": ["27017:27017"],
            "volumes": ["mongo_data:/data/db"],
            "env": {},
        },
        {
            "name": "redis",
            "image": "redis:7-alpine",
            "ports": ["6379:6379"],
            "volumes": ["redis_data:/data"],
            "env": {},
        },
        {
            "name": "nats",
            "image": "nats:2.10-alpine",
            "ports": ["4222:4222", "8222:8222"],
            "volumes": [],
            "env": {},
        },
    ],
}
