"""Next.js + Prisma + PostgreSQL stack template."""

STACK_TEMPLATE = {
    "name": "nextjs_prisma_postgres",
    "display_name": "Next.js + Prisma + PostgreSQL",
    "tech_stack": {
        "language": "typescript",
        "framework": "nextjs",
        "database": "postgresql",
        "orm": "prisma",
        "migration_tool": "prisma",
        "auth": "next-auth",
        "css": "tailwindcss",
        "package_manager": "npm",
        "runtime": "next",
    },
    "base_directory_structure": [
        "src/",
        "src/app/",
        "src/app/layout.tsx",
        "src/app/page.tsx",
        "src/app/globals.css",
        "src/app/api/",
        "src/components/",
        "src/components/ui/",
        "src/lib/",
        "src/lib/prisma.ts",
        "src/lib/auth.ts",
        "src/lib/utils.ts",
        "src/types/",
        "src/types/index.ts",
        "prisma/",
        "prisma/schema.prisma",
        "public/",
        "docker/",
    ],
    "base_dependencies": {
        "runtime": [
            "next@latest",
            "react@latest",
            "react-dom@latest",
            "@prisma/client",
            "next-auth",
            "zod",
            "tailwindcss",
            "postcss",
            "autoprefixer",
            "lucide-react",
        ],
        "dev": [
            "typescript",
            "@types/node",
            "@types/react",
            "@types/react-dom",
            "prisma",
            "eslint",
            "eslint-config-next",
        ],
    },
    "base_env_vars": [
        {
            "name": "DATABASE_URL",
            "description": "PostgreSQL connection string for Prisma",
            "example_value": "postgresql://postgres:postgres@localhost:5432/appdb",
            "required": True,
        },
        {
            "name": "NEXTAUTH_SECRET",
            "description": "NextAuth.js secret for session encryption",
            "example_value": "change-me-in-production",
            "required": True,
        },
        {
            "name": "NEXTAUTH_URL",
            "description": "Base URL of the Next.js application",
            "example_value": "http://localhost:3000",
            "required": False,
        },
    ],
    "base_docker_services": [
        {
            "name": "postgres",
            "image": "postgres:16-alpine",
            "ports": ["5432:5432"],
            "volumes": ["pgdata:/var/lib/postgresql/data"],
            "env": {
                "POSTGRES_USER": "postgres",
                "POSTGRES_PASSWORD": "postgres",
                "POSTGRES_DB": "appdb",
            },
        },
    ],
}
