"""PERN stack template (Postgres + Express + React + Node)."""

STACK_TEMPLATE = {
    "name": "pern_postgres",
    "display_name": "PERN (Postgres + Express + React + Node)",
    "template_dir": "project_templates/pern_postgres",
    "tech_stack": {
        "language": "typescript",
        "framework": "express+react",
        "database": "postgresql",
        "orm": "prisma",
        "migration_tool": "prisma",
        "auth": "jwt",
        "css": "tailwindcss",
        "package_manager": "npm",
        "runtime": "node+vite",
    },
    "base_directory_structure": [
        # Backend
        "app/",
        "app/src/",
        "app/src/index.ts",
        "app/src/routes/",
        "app/src/controllers/",
        "app/src/middleware/",
        "app/src/models/",
        "app/src/db/",
        "app/src/utils/",
        "app/prisma/",
        "app/prisma/schema.prisma",
        # Auth microservice
        "services/",
        "services/auth-service/",
        "services/auth-service/src/",
        "services/auth-service/src/index.ts",
        "services/auth-service/src/routes/",
        "services/auth-service/src/middleware/",
        "services/auth-service/src/db/",
        "services/auth-service/src/utils/",
        "services/auth-service/prisma/",
        "services/auth-service/prisma/schema.prisma",
        # Frontend
        "frontend/",
        "frontend/src/",
        "frontend/src/main.tsx",
        "frontend/src/App.tsx",
        "frontend/src/index.css",
        "frontend/src/components/",
        "frontend/src/pages/",
        "frontend/src/lib/",
        "frontend/src/lib/api.ts",
        "frontend/public/",
        # Infra
        "infra/",
        "infra/docker/",
        "scripts/",
    ],
    "base_dependencies": {
        "runtime": [
            "express",
            "cors",
            "helmet",
            "dotenv",
            "morgan",
            "zod",
            "pg",
            "@prisma/client",
            "jsonwebtoken",
            "bcryptjs",
            "react",
            "react-dom",
            "react-router-dom",
        ],
        "dev": [
            "typescript",
            "tsx",
            "nodemon",
            "vitest",
            "eslint",
            "@typescript-eslint/parser",
            "@typescript-eslint/eslint-plugin",
            "@types/node",
            "@types/express",
            "@types/jsonwebtoken",
            "@types/bcryptjs",
            "@types/cors",
            "@types/morgan",
            "@types/react",
            "@types/react-dom",
            "vite",
            "@vitejs/plugin-react",
            "tailwindcss",
            "postcss",
            "autoprefixer",
            "prisma",
        ],
    },
    "base_env_vars": [
        {
            "name": "NODE_ENV",
            "description": "Runtime environment",
            "example_value": "development",
            "required": False,
        },
        {
            "name": "API_PORT",
            "description": "Express API port",
            "example_value": "3000",
            "required": True,
        },
        {
            "name": "FRONTEND_PORT",
            "description": "Frontend dev server port",
            "example_value": "5173",
            "required": False,
        },
        {
            "name": "JWT_SECRET",
            "description": "JWT signing secret",
            "example_value": "change-me-in-production",
            "required": True,
        },
        {
            "name": "POSTGRES_USER",
            "description": "Postgres user",
            "example_value": "appuser",
            "required": True,
        },
        {
            "name": "POSTGRES_PASSWORD",
            "description": "Postgres password",
            "example_value": "apppassword",
            "required": True,
        },
        {
            "name": "POSTGRES_DB",
            "description": "Postgres database",
            "example_value": "appdb",
            "required": True,
        },
        {
            "name": "DATABASE_URL",
            "description": "Postgres connection string",
            "example_value": "postgresql://appuser:apppassword@localhost:5432/appdb",
            "required": True,
        },
    ],
    "base_docker_services": [
        {
            "name": "postgres",
            "image": "postgres:16-alpine",
            "ports": ["5432:5432"],
            "volumes": ["pgdata:/var/lib/postgresql/data"],
            "environment": {
                "POSTGRES_USER": "appuser",
                "POSTGRES_PASSWORD": "apppassword",
                "POSTGRES_DB": "appdb",
            },
        },
    ],
}
